[package]
name = "spin-cube"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.29"
nalgebra = "0.32"
tokio = { version = "1.44.2", features = ["full"] }
ringbuffer = "0.15.0"